# Generated by Django 3.2.6 on 2021-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=8)),
                ('gender', models.CharField(choices=[('female', 'F'), ('male', 'M')], default=None, max_length=30)),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
    ]
